### ISSUE TITLE
user interactivity - required component for project

### ISSUE THREAD

**Issue by vshulman25** [vshulman25/drinksplease#19]
User needs to decide if they would like alcohol in their drink or not,
Once decision is made pushes to weather api to determine 50 degrees +/- 
Drink is determined from here and displayed

**Comment by duffieldml** [comment]
How do we want the user to decide if they want alcohol or not in their drink? Maybe a question with yes & no options?

**Comment by duffieldml** [comment]
How do we want to populate drinks to the dom? Are we thinking cards, carousel, ect? What info do we want to pull from the returned array? Drink name, ingredients, instructions, jpg of the drink?

**Comment by JGreenOS** [comment]
Note : Make sure to include this in the readme
