### ISSUE TITLE
hot drink names 

### ISSUE THREAD

**Issue by vshulman25** [vshulman25/drinksplease#24]
Afternoon, Karsk, Spiking coffee, Cafe Savoy, Mocha-Berry, Irish Coffee, Hot Creamy Bush, Talos Coffee, Tennessee Mud, Swedish Coffee, Fuzzy Asshole, Jamaican Coffee, Almond Chocolate Coffee, H.D., Kioki Coffee

Amaretto Tea, Masala Chai, Herbal Flame

Rum Toddy, Castillian Hot Chocolate, Chocolate Drink, Microwave Hot Cocoa, Gluehwein, Mulled Wine

**Comment by vshulman25** [comment]
How to pull these out - TBD

**Comment by duffieldml** [comment]
I have included all these into the hot drinks array. It pulls one out randomly use math.random
